export const ui = {
  appShell: document.querySelector<HTMLElement>("#appShell")!,
  form: document.querySelector<HTMLFormElement>("#chatForm")!,
  agentSelect: document.querySelector<HTMLSelectElement>("#agentSelect")!,
  input: document.querySelector<HTMLTextAreaElement>("#queryInput")!,
  sendButton: document.querySelector<HTMLButtonElement>("#sendButton")!,
  hideChatButton: document.querySelector<HTMLButtonElement>("#hideChatButton")!,
  showChatButton: document.querySelector<HTMLButtonElement>("#showChatButton")!,
  chatColumn: document.querySelector<HTMLElement>(".chat-column")!,
  chatLog: document.querySelector<HTMLDivElement>("#chatLog")!,
  chatResizeHandle: document.querySelector<HTMLDivElement>("#chatResizeHandle")!,
  statusList: document.querySelector<HTMLOListElement>("#statusList")!,
  guardrailBadge: document.querySelector<HTMLSpanElement>("#guardrailBadge")!,
  reportTitle: document.querySelector<HTMLHeadingElement>("#reportTitle")!,
  reportMode: document.querySelector<HTMLSpanElement>("#reportMode")!,
  reportSummary: document.querySelector<HTMLParagraphElement>("#reportSummary")!,
  portfolioMeta: document.querySelector<HTMLSpanElement>("#portfolioMeta")!,
  portfolioPositions: document.querySelector<HTMLDivElement>("#portfolioPositions")!,
  allocationSort: document.querySelector<HTMLSelectElement>("#allocationSort")!,
  allocationChart: document.querySelector<HTMLDivElement>("#allocationChart")!,
  allocationViewButtons: Array.from(
    document.querySelectorAll<HTMLButtonElement>("[data-allocation-view]"),
  ),
  portfolioEvaluation: document.querySelector<HTMLDivElement>("#portfolioEvaluation")!,
  recommendationsList: document.querySelector<HTMLUListElement>("#recommendationsList")!,
  missingDataList: document.querySelector<HTMLUListElement>("#missingDataList")!,
  sentimentList: document.querySelector<HTMLDivElement>("#sentimentList")!,
  citationList: document.querySelector<HTMLDivElement>("#citationList")!,
  traceOutput: document.querySelector<HTMLPreElement>("#traceOutput")!,
};
